[package]
name = "shop-ui"
version = "0.1.0"
authors = ["Stuart Todd <hello@halfshellstudios.co.uk>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.7.1", features = [] }
dioxus-router = "0.7.3"
gloo-net = "0.6.0"
gloo-storage = "0.3.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
